default: &default
  adapter: mysql2
  database: findbook
  host: localhost
  username: root
  port: 3306
  pool: 25
  encoding: utf8

development:
  <<: *default

test:
  <<: *default
  database: findbook_test
